"""change model schema

Revision ID: 019ef3743836
Revises: fa30cd335348
Create Date: 2025-12-16 12:19:12.650177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '019ef3743836'
down_revision: Union[str, Sequence[str], None] = 'fa30cd335348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'timestamp')
    op.drop_column('transactions', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('transactions', sa.Column('timestamp', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True))
    # ### end Alembic commands ###
