"""fix autoincrement on id

Revision ID: ed8eb0314adb
Revises: 078ec5eb9ec1
Create Date: 2025-12-16 10:25:38.183073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ed8eb0314adb'
down_revision: Union[str, Sequence[str], None] = '078ec5eb9ec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'type',
               existing_type=mysql.ENUM('credit', 'debit'),
               type_=sa.Enum('income', 'expense', name='transactiontype'),
               existing_nullable=False)
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.alter_column('transactions', 'type',
               existing_type=sa.Enum('income', 'expense', name='transactiontype'),
               type_=mysql.ENUM('credit', 'debit'),
               existing_nullable=False)
    # ### end Alembic commands ###
